### ISSUE TITLE
Bot is not responding

### ISSUE THREAD

**Issue by msieche** [MrAuro/OuraEmotes#77]
Currently the bot doesn't respond to any command on our discord server.
I tried to fix it by:
- removing the integration and inviting the bot again
- double checking that the "Manage Emojis and Stickers" permission is granted for the "BTTV Emotes" role

On this screenshot you can see that it worked perfectly fine back in December:
![image](https://user-images.githubusercontent.com/14164172/149225862-6beaf48c-90de-4417-9b3d-84f3a433ee8f.png)

Do you have any idea or tips what could have changed so that the bot doesn't respond anymore? It's currently the only bot on our server.

Thanks in advance :)

**Comment by MrAuro** [comment]
Seems the bot went down. It is now up again for you to use :) Thanks for letting me know!
